const enum Message {
  STUDENT_ALREADY_EXISTS = "STUDENT_ALREADY_EXISTS",
  STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
  STUDENT_TOO_MANY_ATTEMPTS = "STUDENT_TOO_MANY_ATTEMPTS",
  STUDENT_CREATED_SUCCESSFULLY = "STUDENT_CREATED_SUCCESSFULLY",
  STUDENT_UPDATED_SUCCESSFULLY = "STUDENT_UPDATED_SUCCESSFULLY",
  STUDENT_FETCH_SUCCESSFULLY = "STUDENT_FETCH_SUCCESSFULLY",
  STUDENT_DELETED_SUCCESSFULLY = "STUDENT_DELETED_SUCCESSFULLY",
  NO_STUDENT_FOUND = "NO_STUDENT_FOUND",

  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  BAD_REQUEST = "BAD REQUEST",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
}

export { Message };
